### ISSUE TITLE
usePolygon

### ISSUE THREAD

**Issue by kevinsherman** [117/alpaca#20]
hello, i don't see a configuration option to use polygon. what's the recommended approach for this, per: https://github.com/alpacahq/alpaca-trade-api-js/blob/master/lib/alpaca-trade-api.js

usePolygon: config.usePolygon ? true : false, // should we use polygon
                                                  // data or alpaca data

**Comment by 117** [comment]
Alpaca has stated in the docs that ["The plan is to eventually provide everything through Alpaca Data API at some point."](https://alpaca.markets/docs/api-documentation/api-v2/market-data/). I'm not inclined to add polygon for this reason.

If you still want Polygon.io to be included since it is a part of the Alpaca market data... then I agree that it should probably be here for everyone else who isn't me (even though I don't like polygon's history of unreliability)!

If you submitted a pull request to the [dev](https://github.com/117/alpaca/tree/dev) branch I would gladly work with you to merge it into the existing package.
